### ISSUE TITLE
Double notification on already triggered devices

### ISSUE THREAD

**Issue by bjoern812** [maros/Zway-SecurityZone#3]
Dear Maros,

I have a little issue with your module. If you define a Zone with an "Activation delay" and an "Alarm check"
which should be checked immediate if the condition already triggered, then a get a double notification
warning.

IMHO, is seems that the device is checked twice, once in line 348
`self.checkActivate(['immediate']);`
and also in line 354 (where the delayed activation is handled):
`self.checkActivate(['immediate','delayed']);`

I tested changing the line 354 to
`self.checkActivate(['delayed']);`
and I get only one notification.

Thanks in advance
Björn

**Comment by bjoern812** [comment]
Hi again,

sorry for my fast reply, but I notice that if I change the line 354 to
`self.checkActivate(['delayed']);`
and define a zone with a "Activation delay" of zero, then no notification is
send, if the device is already triggered.
So the code change is "suboptimal".

Björn

**Comment by bjoern812** [comment]
Hello again,

after changing the line 354 to something like that:
`        if (state === 'delayActivate') {
            self.checkActivate(['delayed']);
        } else {
          self.checkActivate(['immediate','delayed']);
        }
`
I get in both scenarios ("Activation delay" set and unset) only
one notification. But I'm not sure, if this works for all possible
scenarios.

Björn

**Comment by maros** [comment]
Thank you for your bug report. This issue was fixed in version 1.12
