### ISSUE TITLE
Double notification on already triggered devices

### ISSUE THREAD

**Issue by bjoern812** [maros/Zway-SecurityZone#4]
Dear Maros,

thank for fixing the issue #3 , but the problem of double notification is still there.
I forgot to tell you to delete line 358 (the line after the new if/then/else):
`self.checkActivate(['immediate','delayed']);`

Sorry for my late reply/test of this.

Thanks. Björn.

**Comment by maros** [comment]
This issue was fixed via aec27f55f092ddc0aee58a0051c6e9c1a7f45b22 and should be available in 1.13
